# Generated by Django 5.2.4 on 2025-07-30 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('选择题', '选择题'), ('填空题', '填空题'), ('判断题', '判断题'), ('简答题', '简答题'), ('证明题', '证明题')], max_length=10, verbose_name='题型')),
                ('text', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='选项（选择题专用）')),
                ('answer', models.TextField(verbose_name='答案')),
                ('difficulty', models.CharField(choices=[('简单', '简单'), ('中等', '中等'), ('困难', '困难')], default='中等', max_length=2, verbose_name='难度')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成时间')),
                ('json_file_path', models.CharField(blank=True, max_length=255, verbose_name='对应JSON文件路径')),
                ('knowledge_point', models.TextField(blank=True, null=True, verbose_name='考点')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='解析')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '生成的题目',
                'verbose_name_plural': '生成的题目',
            },
        ),
        migrations.CreateModel(
            name='QuestionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('current_question_index', models.IntegerField(default=0, verbose_name='当前题目索引')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('questions', models.ManyToManyField(to='questions.generatedquestion', verbose_name='题目列表')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '答题会话',
                'verbose_name_plural': '答题会话',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='用户答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.generatedquestion', verbose_name='题目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
            },
        ),
    ]
